[2023-12-13 17:20:25] [info] server.go:616 dpchain/p2p/server.(*Server).setupConn p2pServer等待完成与目标节点(127.0.0.1:20130)的加密handshake与协议handshake!

[2023-12-13 17:20:25] [info] server.go:602 dpchain/p2p/server.(*Server).listenLoop 接收到来自节点 127.0.0.1:63957的p2p连接请求

[2023-12-13 17:20:25] [info] server.go:616 dpchain/p2p/server.(*Server).setupConn p2pServer等待完成与目标节点(127.0.0.1:63957)的加密handshake与协议handshake!

[2023-12-13 17:20:25] [info] server.go:636 dpchain/p2p/server.(*Server).setupConn p2pServer完成与目标节点(127.0.0.1:63957)的加密handshake!

[2023-12-13 17:20:25] [info] server.go:643 dpchain/p2p/server.(*Server).setupConn 下面进行加密handshake的 checkpoint!!! ,127.0.0.1:63957 

[2023-12-13 17:20:25] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn inbound conn 4e42a659d605711a 127.0.0.1:63957 failed checkpoint posthandshake: Connected to self
[2023-12-13 17:20:25] [info] server.go:636 dpchain/p2p/server.(*Server).setupConn p2pServer完成与目标节点(127.0.0.1:20130)的加密handshake!

[2023-12-13 17:20:25] [info] server.go:643 dpchain/p2p/server.(*Server).setupConn 下面进行加密handshake的 checkpoint!!! ,127.0.0.1:20130 

[2023-12-13 17:20:25] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn dyn dial conn 4e42a659d605711a 127.0.0.1:20130 failed checkpoint posthandshake: Connected to self
[2023-12-13 17:20:29] [info] peer.go:76 dpchain/core/separator.(*peer).sendMsg Separator: Send msg to peer: cce471fc46e9402940bb2bcc4fbcee724dfcc14e020f6362ec2ad827bf6c4ef7354165b9de64807d37caae4888c31a86c34b77594ee64be150612991f6e95b61, msgcode: 3

[2023-12-13 17:20:29] [info] orderServer.go:430 dpchain/core/blockOrdering.(*BlockOrderServer).tryLaunchNewRound [Block Ordering] A new next message is generated and sent, version: 0000000000000000000000000000000000000000000000000000000000000000, height: 0, BlockID: dbaef331c1564a2e63593b55571f51c217e1bcf8b8523abf324ef76975279685

[2023-12-13 17:20:29] [info] peer.go:76 dpchain/core/separator.(*peer).sendMsg Separator: Send msg to peer: cce471fc46e9402940bb2bcc4fbcee724dfcc14e020f6362ec2ad827bf6c4ef7354165b9de64807d37caae4888c31a86c34b77594ee64be150612991f6e95b61, msgcode: 3

[2023-12-13 17:20:57] [info] server.go:616 dpchain/p2p/server.(*Server).setupConn p2pServer等待完成与目标节点(127.0.0.1:20130)的加密handshake与协议handshake!

[2023-12-13 17:20:57] [info] server.go:602 dpchain/p2p/server.(*Server).listenLoop 接收到来自节点 127.0.0.1:64080的p2p连接请求

[2023-12-13 17:20:57] [info] server.go:616 dpchain/p2p/server.(*Server).setupConn p2pServer等待完成与目标节点(127.0.0.1:64080)的加密handshake与协议handshake!

[2023-12-13 17:20:57] [info] server.go:636 dpchain/p2p/server.(*Server).setupConn p2pServer完成与目标节点(127.0.0.1:64080)的加密handshake!

[2023-12-13 17:20:57] [info] server.go:643 dpchain/p2p/server.(*Server).setupConn 下面进行加密handshake的 checkpoint!!! ,127.0.0.1:64080 

[2023-12-13 17:20:57] [info] server.go:636 dpchain/p2p/server.(*Server).setupConn p2pServer完成与目标节点(127.0.0.1:20130)的加密handshake!

[2023-12-13 17:20:57] [info] server.go:643 dpchain/p2p/server.(*Server).setupConn 下面进行加密handshake的 checkpoint!!! ,127.0.0.1:20130 

[2023-12-13 17:20:57] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn inbound conn 4e42a659d605711a 127.0.0.1:64080 failed checkpoint posthandshake: Connected to self
[2023-12-13 17:20:57] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn dyn dial conn 4e42a659d605711a 127.0.0.1:20130 failed checkpoint posthandshake: Connected to self
