[2023-12-13 17:14:04] [info] server.go:602 dpchain/p2p/server.(*Server).listenLoop 接收到来自节点 127.0.0.1:61392的p2p连接请求

[2023-12-13 17:14:04] [info] server.go:616 dpchain/p2p/server.(*Server).setupConn p2pServer等待完成与目标节点(127.0.0.1:61392)的加密handshake与协议handshake!

[2023-12-13 17:14:04] [info] server.go:616 dpchain/p2p/server.(*Server).setupConn p2pServer等待完成与目标节点(127.0.0.1:20133)的加密handshake与协议handshake!

[2023-12-13 17:14:04] [info] server.go:636 dpchain/p2p/server.(*Server).setupConn p2pServer完成与目标节点(127.0.0.1:61392)的加密handshake!

[2023-12-13 17:14:04] [info] server.go:643 dpchain/p2p/server.(*Server).setupConn 下面进行加密handshake的 checkpoint!!! ,127.0.0.1:61392 

[2023-12-13 17:14:04] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn inbound conn 60dc34b7697c9058 127.0.0.1:61392 failed checkpoint posthandshake: Connected to self
[2023-12-13 17:14:04] [info] server.go:636 dpchain/p2p/server.(*Server).setupConn p2pServer完成与目标节点(127.0.0.1:20133)的加密handshake!

[2023-12-13 17:14:04] [info] server.go:643 dpchain/p2p/server.(*Server).setupConn 下面进行加密handshake的 checkpoint!!! ,127.0.0.1:20133 

[2023-12-13 17:14:04] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn dyn dial conn 60dc34b7697c9058 127.0.0.1:20133 failed checkpoint posthandshake: Connected to self
[2023-12-13 17:14:36] [info] server.go:616 dpchain/p2p/server.(*Server).setupConn p2pServer等待完成与目标节点(127.0.0.1:20133)的加密handshake与协议handshake!

[2023-12-13 17:14:36] [info] server.go:602 dpchain/p2p/server.(*Server).listenLoop 接收到来自节点 127.0.0.1:61599的p2p连接请求

[2023-12-13 17:14:36] [info] server.go:616 dpchain/p2p/server.(*Server).setupConn p2pServer等待完成与目标节点(127.0.0.1:61599)的加密handshake与协议handshake!

[2023-12-13 17:14:36] [info] server.go:636 dpchain/p2p/server.(*Server).setupConn p2pServer完成与目标节点(127.0.0.1:61599)的加密handshake!

[2023-12-13 17:14:36] [info] server.go:643 dpchain/p2p/server.(*Server).setupConn 下面进行加密handshake的 checkpoint!!! ,127.0.0.1:61599 

[2023-12-13 17:14:36] [info] server.go:636 dpchain/p2p/server.(*Server).setupConn p2pServer完成与目标节点(127.0.0.1:20133)的加密handshake!

[2023-12-13 17:14:36] [info] server.go:643 dpchain/p2p/server.(*Server).setupConn 下面进行加密handshake的 checkpoint!!! ,127.0.0.1:20133 

[2023-12-13 17:14:36] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn inbound conn 60dc34b7697c9058 127.0.0.1:61599 failed checkpoint posthandshake: Connected to self
[2023-12-13 17:14:36] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn dyn dial conn 60dc34b7697c9058 127.0.0.1:20133 failed checkpoint posthandshake: Connected to self
[2023-12-13 17:14:37] [info] dper.go:234 dpchain/ginHttp/router/api.InitRouter.BackAccountList.func16 Http: Get user request -- BackAccountList

[2023-12-13 17:14:37] [info] dper.go:244 dpchain/ginHttp/router/api.InitRouter.BackAccountList.func16 Http: Reply to user request -- BackAccountList  succeed!

[2023-12-13 17:14:37] [info] dper.go:286 dpchain/ginHttp/router/api.InitRouter.UseAccount.func18 Http: Get user request -- UseAccount  account:e3ecbde812371d28babdef11f9e6e90a37c945d2

[2023-12-13 17:14:37] [info] dper.go:302 dpchain/ginHttp/router/api.InitRouter.UseAccount.func18 Http: Reply to user request -- UseAccount  succeed!

[2023-12-13 17:14:38] [info] dper.go:331 dpchain/ginHttp/router/api.InitRouter.OpenTxCheckMode.func20 Http: Get user request -- OpenTxCheckMode  mode:on

[2023-12-13 17:14:38] [info] dperCommand.go:379 dpchain/dper/client/commandLine.(*CommandLine).handleTxCheckMode Dper: handleTxCheckMode runs successfully, The current Tx check mode is on

[2023-12-13 17:14:38] [info] dper.go:342 dpchain/ginHttp/router/api.InitRouter.OpenTxCheckMode.func20 Http: Reply to user request -- OpenTxCheckMode  succeed!

