[2023-12-13 17:26:20] [info] server.go:616 dpchain/p2p/server.(*Server).setupConn p2pServer等待完成与目标节点(127.0.0.1:20132)的加密handshake与协议handshake!

[2023-12-13 17:26:20] [info] server.go:602 dpchain/p2p/server.(*Server).listenLoop 接收到来自节点 127.0.0.1:49543的p2p连接请求

[2023-12-13 17:26:20] [info] server.go:616 dpchain/p2p/server.(*Server).setupConn p2pServer等待完成与目标节点(127.0.0.1:49543)的加密handshake与协议handshake!

[2023-12-13 17:26:20] [info] server.go:636 dpchain/p2p/server.(*Server).setupConn p2pServer完成与目标节点(127.0.0.1:49543)的加密handshake!

[2023-12-13 17:26:20] [info] server.go:643 dpchain/p2p/server.(*Server).setupConn 下面进行加密handshake的 checkpoint!!! ,127.0.0.1:49543 

[2023-12-13 17:26:20] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn inbound conn 7d0efb28d2df0371 127.0.0.1:49543 failed checkpoint posthandshake: Connected to self
[2023-12-13 17:26:20] [info] server.go:636 dpchain/p2p/server.(*Server).setupConn p2pServer完成与目标节点(127.0.0.1:20132)的加密handshake!

[2023-12-13 17:26:20] [info] server.go:643 dpchain/p2p/server.(*Server).setupConn 下面进行加密handshake的 checkpoint!!! ,127.0.0.1:20132 

[2023-12-13 17:26:20] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn dyn dial conn 7d0efb28d2df0371 127.0.0.1:20132 failed checkpoint posthandshake: Connected to self
[2023-12-13 17:26:33] [info] separator.go:119 dpchain/core/separator.(*Separator).handlePeer.func1 与节点(4e42a659d605711a25445c4253c0ca08636349d80dd5c30f6853d95c01b537ccde24123f6ee72d003112fc77a93fe60bf8f6a27e83d27e2875a385004f9a1fc7)断开separator handshake!

[2023-12-13 17:26:33] [warning] peer.go:319 dpchain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2023-12-13 17:26:33] [info] whisper.go:221 dpchain/p2p/whisper.(*Whisper).handlePeer.func1 与节点 (3465343261363539643630353731316132353434356334323533633063613038363336333439643830646435633330663638353364393563303162353337636364653234313233663665653732643030333131326663373761393366653630626638663661323765383364323765323837356133383530303466396131666337) 断开 whisper handshake!

[2023-12-13 17:26:33] [warning] peer.go:319 dpchain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2023-12-13 17:26:33] [warning] peer.go:208 dpchain/p2p/server.(*Peer).pingLoop heart beate, ping协程退出

[2023-12-13 17:26:33] [info] server.go:717 dpchain/p2p/server.(*Server).runPeer Remove Protocal peer (NodeID:3465343261363539643630353731316132353434356334323533633063613038363336333439643830646435633330663638353364393563303162353337636364653234313233663665653732643030333131326663373761393366653630626638663661323765383364323765323837356133383530303466396131666337) (srcIPAddr:127.0.0.1:20132) (destIPAddr:127.0.0.1:61210) ,err:Network error

[2023-12-13 17:26:33] [error] dial.go:217 dpchain/p2p/server.(*dialTask).Do dial error: dial tcp 127.0.0.1:20130: connect: connection refused
[2023-12-13 17:26:33] [info] separator.go:119 dpchain/core/separator.(*Separator).handlePeer.func1 与节点(cce471fc46e9402940bb2bcc4fbcee724dfcc14e020f6362ec2ad827bf6c4ef7354165b9de64807d37caae4888c31a86c34b77594ee64be150612991f6e95b61)断开separator handshake!

[2023-12-13 17:26:33] [warning] peer.go:319 dpchain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2023-12-13 17:26:33] [info] whisper.go:221 dpchain/p2p/whisper.(*Whisper).handlePeer.func1 与节点 (6363653437316663343665393430323934306262326263633466626365653732346466636331346530323066363336326563326164383237626636633465663733353431363562396465363438303764333763616165343838386333316138366333346237373539346565363462653135303631323939316636653935623631) 断开 whisper handshake!

[2023-12-13 17:26:33] [warning] peer.go:319 dpchain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2023-12-13 17:26:33] [warning] peer.go:208 dpchain/p2p/server.(*Peer).pingLoop heart beate, ping协程退出

[2023-12-13 17:26:33] [info] server.go:717 dpchain/p2p/server.(*Server).runPeer Remove Protocal peer (NodeID:6363653437316663343665393430323934306262326263633466626365653732346466636331346530323066363336326563326164383237626636633465663733353431363562396465363438303764333763616165343838386333316138366333346237373539346565363462653135303631323939316636653935623631) (srcIPAddr:127.0.0.1:20132) (destIPAddr:127.0.0.1:61233) ,err:Network error

[2023-12-13 17:26:33] [warning] synchronization.go:205 dpchain/blockSync.(*SyncProtocal).handleMsg Block synchronization failed: Couldn't Read the next message from the remote peer (cce471fc46e9402940bb2bcc4fbcee724dfcc14e020f6362ec2ad827bf6c4ef7354165b9de64807d37caae4888c31a86c34b77594ee64be150612991f6e95b61), err:EOF

[2023-12-13 17:26:33] [error] dial.go:217 dpchain/p2p/server.(*dialTask).Do dial error: dial tcp 127.0.0.1:20131: connect: connection refused
[2023-12-13 17:26:33] [info] daemonClose.go:42 main.main [Daemon]  Dper Client is running in PID: 88583

[2023-12-13 17:26:33] [info] daemonClose.go:61 main.main [Daemon] PID :88583 has been killed!

